### ISSUE TITLE
Install on Capacitor 2.  ¿any workaround?

### ISSUE THREAD

**Issue by ealbinu** [capacitor-community/screen-brightness#1]
**Describe the bug**
Couldn't install on Capacitor 2.

**To Reproduce**
1. On a regular Capacitor 2 project.
2. npm install @capacitor-community/screen-brightness
3. 
> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: appname@1.0.73
npm ERR! Found: @capacitor/core@2.4.7
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0-beta.3" from @capacitor-community/screen-brightness@1.0.0
npm ERR! node_modules/@capacitor-community/screen-brightness
npm ERR!   @capacitor-community/screen-brightness@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/username/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-04-26T23_56_34_109Z-debug.log
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOs 11.2.3
 - Version: Capacitor 2

**Additional context**
¿Is the a workaround to install this plugin or am i doing something wrong?.

Thnks.

**Comment by elylucas** [comment]
The plugin has Capacitor 3 support only.
