### ISSUE TITLE
getBrightness() initially always returns -1

### ISSUE THREAD

**Issue by mobilemarines** [capacitor-community/screen-brightness#3]
**Describe the bug**
When calling getBrightness() the first time it always returns -1 (documented range should be 0-1).
As soon as the brightness is set with setBrightness() the set value is correctly returned with getBrightness().
But that way you cannot compare the initial brightness the app starts with. But you can revert it by setting -1.
It makes no difference if Auto-brightness/Adaptive brightness is enabled or disabled.

**To Reproduce**
1. Call getBrightness() before calling setBrightness()

**Expected behavior**
Returns the current brightness level (range 0-1) the app starts with.

**Desktop:**
 - OS: Android 11
 - Browser: Chrome
 - Version: 92.0.4515.131

**Smartphone:**
 - Device: Google Pixel 3a
 - OS: Android 11
 - Browser: Chrome
 - Version: 92.0.4515.131

**Additional context**
Seems that every Android version is affected. Also tested on Android 9.

**Comment by tomfong** [comment]
According to [WindowManager.LayoutParams document](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#screenBrightness), -1.0 is the **"default value for [screenBrightness](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#screenBrightness) and [buttonBrightness](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#buttonBrightness) indicating that the brightness value is not overridden for this window and normal brightness policy should be used.**

**Comment by mobilemarines** [comment]
Thanks @tomfong for pointing that out.
Getting the absolute value of this default would be great.
Otherwise the getter is kind of useless expect for querying what you just set.

**Comment by tomfong** [comment]
> Thanks @tomfong for pointing that out.
> Getting the absolute value of this default would be great.
> Otherwise the getter is kind of useless expect for querying what you just set.

It looks like the getter is for iOS only.
